from __future__ import annotations

from models import Truck, TruckKit, now_iso
from stages import Stage


def build_sample_trucks() -> list[Truck]:
    now_value = now_iso()

    truck_1049 = Truck(
        id=1,
        truck_number="Truck1049",
        notes="Sample current fabrication truck",
        created_at=now_value,
        updated_at=now_value,
        kits=[
            TruckKit(
                id=101,
                truck_id=1,
                kit_template_id=1,
                parent_kit_id=None,
                kit_name="Pumphouse",
                kit_order=1,
                is_main_kit=False,
                release_state="released",
                front_stage_id=int(Stage.COMPLETE),
                back_stage_id=int(Stage.COMPLETE),
                blocker="",
                is_active=True,
                created_at=now_value,
                updated_at=now_value,
            ),
            TruckKit(
                id=102,
                truck_id=1,
                kit_template_id=2,
                parent_kit_id=None,
                kit_name="Console Pack",
                kit_order=2,
                is_main_kit=False,
                release_state="released",
                front_stage_id=int(Stage.COMPLETE),
                back_stage_id=int(Stage.COMPLETE),
                blocker="",
                is_active=True,
                created_at=now_value,
                updated_at=now_value,
            ),
            TruckKit(
                id=103,
                truck_id=1,
                kit_template_id=3,
                parent_kit_id=None,
                kit_name="Body",
                kit_order=3,
                is_main_kit=True,
                release_state="released",
                front_stage_id=int(Stage.WELD),
                back_stage_id=int(Stage.BEND),
                blocker="",
                is_active=True,
                created_at=now_value,
                updated_at=now_value,
            ),
            TruckKit(
                id=104,
                truck_id=1,
                kit_template_id=4,
                parent_kit_id=None,
                kit_name="Interior Pack",
                kit_order=4,
                is_main_kit=False,
                release_state="released",
                front_stage_id=int(Stage.LASER),
                back_stage_id=int(Stage.LASER),
                blocker="Bent parts waiting",
                is_active=True,
                created_at=now_value,
                updated_at=now_value,
            ),
            TruckKit(
                id=105,
                truck_id=1,
                kit_template_id=5,
                parent_kit_id=None,
                kit_name="Exterior Pack",
                kit_order=5,
                is_main_kit=False,
                release_state="not_released",
                front_stage_id=int(Stage.RELEASE),
                back_stage_id=int(Stage.RELEASE),
                blocker="Awaiting drawings",
                is_active=True,
                created_at=now_value,
                updated_at=now_value,
            ),
        ],
    )

    truck_1050 = Truck(
        id=2,
        truck_number="Truck1050",
        notes="Sample upcoming fabrication truck",
        created_at=now_value,
        updated_at=now_value,
        kits=[
            TruckKit(
                id=201,
                truck_id=2,
                kit_template_id=1,
                parent_kit_id=None,
                kit_name="Pumphouse",
                kit_order=1,
                is_main_kit=False,
                release_state="not_released",
                front_stage_id=int(Stage.RELEASE),
                back_stage_id=int(Stage.RELEASE),
                blocker="",
                is_active=True,
                created_at=now_value,
                updated_at=now_value,
            ),
            TruckKit(
                id=202,
                truck_id=2,
                kit_template_id=2,
                parent_kit_id=None,
                kit_name="Console Pack",
                kit_order=2,
                is_main_kit=False,
                release_state="released",
                front_stage_id=int(Stage.BEND),
                back_stage_id=int(Stage.LASER),
                blocker="Waiting for remaining parts",
                is_active=True,
                created_at=now_value,
                updated_at=now_value,
            ),
            TruckKit(
                id=203,
                truck_id=2,
                kit_template_id=3,
                parent_kit_id=None,
                kit_name="Body",
                kit_order=3,
                is_main_kit=True,
                release_state="not_released",
                front_stage_id=int(Stage.RELEASE),
                back_stage_id=int(Stage.RELEASE),
                blocker="Body package not released",
                is_active=True,
                created_at=now_value,
                updated_at=now_value,
            ),
            TruckKit(
                id=204,
                truck_id=2,
                kit_template_id=4,
                parent_kit_id=None,
                kit_name="Interior Pack",
                kit_order=4,
                is_main_kit=False,
                release_state="not_released",
                front_stage_id=int(Stage.RELEASE),
                back_stage_id=int(Stage.RELEASE),
                blocker="",
                is_active=True,
                created_at=now_value,
                updated_at=now_value,
            ),
            TruckKit(
                id=205,
                truck_id=2,
                kit_template_id=5,
                parent_kit_id=None,
                kit_name="Exterior Pack",
                kit_order=5,
                is_main_kit=False,
                release_state="not_released",
                front_stage_id=int(Stage.RELEASE),
                back_stage_id=int(Stage.RELEASE),
                blocker="",
                is_active=True,
                created_at=now_value,
                updated_at=now_value,
            ),
        ],
    )

    truck_1051 = Truck(
        id=3,
        truck_number="Truck1051",
        notes="Sample future truck",
        created_at=now_value,
        updated_at=now_value,
        kits=[
            TruckKit(
                id=301,
                truck_id=3,
                kit_template_id=1,
                parent_kit_id=None,
                kit_name="Pumphouse",
                kit_order=1,
                is_main_kit=False,
                release_state="not_released",
                front_stage_id=int(Stage.RELEASE),
                back_stage_id=int(Stage.RELEASE),
                blocker="",
                is_active=True,
                created_at=now_value,
                updated_at=now_value,
            ),
            TruckKit(
                id=302,
                truck_id=3,
                kit_template_id=2,
                parent_kit_id=None,
                kit_name="Console Pack",
                kit_order=2,
                is_main_kit=False,
                release_state="not_released",
                front_stage_id=int(Stage.RELEASE),
                back_stage_id=int(Stage.RELEASE),
                blocker="",
                is_active=True,
                created_at=now_value,
                updated_at=now_value,
            ),
            TruckKit(
                id=303,
                truck_id=3,
                kit_template_id=3,
                parent_kit_id=None,
                kit_name="Body",
                kit_order=3,
                is_main_kit=True,
                release_state="not_released",
                front_stage_id=int(Stage.RELEASE),
                back_stage_id=int(Stage.RELEASE),
                blocker="",
                is_active=True,
                created_at=now_value,
                updated_at=now_value,
            ),
            TruckKit(
                id=304,
                truck_id=3,
                kit_template_id=4,
                parent_kit_id=None,
                kit_name="Interior Pack",
                kit_order=4,
                is_main_kit=False,
                release_state="not_released",
                front_stage_id=int(Stage.RELEASE),
                back_stage_id=int(Stage.RELEASE),
                blocker="",
                is_active=True,
                created_at=now_value,
                updated_at=now_value,
            ),
            TruckKit(
                id=305,
                truck_id=3,
                kit_template_id=5,
                parent_kit_id=None,
                kit_name="Exterior Pack",
                kit_order=5,
                is_main_kit=False,
                release_state="not_released",
                front_stage_id=int(Stage.RELEASE),
                back_stage_id=int(Stage.RELEASE),
                blocker="",
                is_active=True,
                created_at=now_value,
                updated_at=now_value,
            ),
        ],
    )

    return [truck_1049, truck_1050, truck_1051]
